@url = https://bug-free-space-spoon-wrvrgx99px57hvg5j-8080.app.github.dev/tarefas

POST {{url}}
Content-Type: application/json

{
    "id": 2,
    "descricao": "Segunda tarefa."
}

###

GET {{url}}

###

###

GET {{url}}/2

###

PUT {{url}}/4
Content-Type: application/json

{
    "descricao": "Teste Alterado"
}

### 

DELETE {{url}}/2